/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package railrider.view;

import java.sql.SQLException;
import static railrider.RailRider.mainFrame;
import railrider.standards.CombinePanel;
import railrider.standards.SessionManager;
import railrider.view.user.BookTicketPanel;
import railrider.view.user.PassDetailsPanel;
import railrider.view.user.PaymentPanel;
import railrider.view.user.TrainsPanel;

/**
 *
 * @author MSI
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
        new CombinePanel(subHomePanel,new BookTicketPanel());
        userNameLabel.setText("Welcome "+SessionManager.getEmail());
    }
    public HomePanel(String s,String d,String date){
        initComponents();
        new CombinePanel(subHomePanel,new TrainsPanel(s,d,date));
        userNameLabel.setText("Welcome "+SessionManager.getEmail());
    }
    public HomePanel(int id,String date){
        initComponents();
        new CombinePanel(subHomePanel,new PassDetailsPanel(id,date));
        userNameLabel.setText("Welcome "+SessionManager.getEmail());
    }
    public HomePanel(int id,String date,String name,String age,String gender) throws SQLException{
        initComponents();
        new CombinePanel(subHomePanel,new PaymentPanel(id,date,name,age,gender));
        userNameLabel.setText("Welcome "+SessionManager.getEmail());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        userNameLabel = new javax.swing.JLabel();
        sideMenuPanel = new javax.swing.JPanel();
        bookTIcketButton = new javax.swing.JButton();
        prnButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        myBookingButton = new javax.swing.JButton();
        settingButton = new javax.swing.JButton();
        subHomePanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setPreferredSize(new java.awt.Dimension(1100, 650));

        headerPanel.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RailRider");

        jButton1.setBackground(new java.awt.Color(255, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        userNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("Welcome");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userNameLabel)
                .addGap(223, 223, 223)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sideMenuPanel.setBackground(new java.awt.Color(24, 119, 242));

        bookTIcketButton.setBackground(new java.awt.Color(255, 51, 0));
        bookTIcketButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bookTIcketButton.setForeground(new java.awt.Color(255, 255, 255));
        bookTIcketButton.setText("BookTicket");
        bookTIcketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTIcketButtonActionPerformed(evt);
            }
        });

        prnButton.setBackground(new java.awt.Color(255, 51, 0));
        prnButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        prnButton.setForeground(new java.awt.Color(255, 255, 255));
        prnButton.setText("PRN Status");

        cancelButton.setBackground(new java.awt.Color(255, 51, 0));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel Ticket");

        myBookingButton.setBackground(new java.awt.Color(255, 51, 0));
        myBookingButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        myBookingButton.setForeground(new java.awt.Color(255, 255, 255));
        myBookingButton.setText("My Bookings");

        settingButton.setBackground(new java.awt.Color(255, 51, 0));
        settingButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        settingButton.setForeground(new java.awt.Color(255, 255, 255));
        settingButton.setText("Settings");

        javax.swing.GroupLayout sideMenuPanelLayout = new javax.swing.GroupLayout(sideMenuPanel);
        sideMenuPanel.setLayout(sideMenuPanelLayout);
        sideMenuPanelLayout.setHorizontalGroup(
            sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bookTIcketButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(prnButton, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
            .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
            .addComponent(myBookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
            .addComponent(settingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        sideMenuPanelLayout.setVerticalGroup(
            sideMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(bookTIcketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(prnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(myBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(settingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        subHomePanel.setLayout(new javax.swing.BoxLayout(subHomePanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(subHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sideMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
      SessionManager.setLoggedIn(false);
      SessionManager.setSno(0);
      SessionManager.setEmail("");
      LoginPanel loginPanel = new LoginPanel();
      mainFrame.setContentPane(loginPanel);
      mainFrame.pack();
      mainFrame.setVisible(true);
     // new CombinePanel(SubHomePanel,new LoginPanel());
      }
      catch(SQLException e)
      {
        e.printStackTrace();
      } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookTIcketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTIcketButtonActionPerformed
        // TODO add your handling code here:
        new CombinePanel(subHomePanel,new BookTicketPanel());
    }//GEN-LAST:event_bookTIcketButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookTIcketButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton myBookingButton;
    private javax.swing.JButton prnButton;
    private javax.swing.JButton settingButton;
    private javax.swing.JPanel sideMenuPanel;
    private javax.swing.JPanel subHomePanel;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
